apiVersion: v1
data:
  AvailabilityDomain: R3JDaDpVUy1BU0hCVVJOLUFELTE=
  Endpoints: W3siaXBBZGRyZXNzIjoiMTAuMC4xMC43IiwicG9ydCI6MzMwNiwicG9ydFgiOjMzMDYwLCJob3N0bmFtZSI6bnVsbCwibW9kZXMiOlsiUkVBRCIsIldSSVRFIl0sInN0YXR1cyI6IkFDVElWRSIsInN0YXR1c0RldGFpbHMiOm51bGx9XQo=
  FaultDomain: RkFVTFQtRE9NQUlOLTE=
  InternalFQDN: ""
  MySQLPort: MzMwNg==
  MySQLXProtocolPort: MzMwNjA=
  PrivateIPAddress: MTAuMC4xMC43
kind: Secret
metadata:
  creationTimestamp: "2022-01-13T21:17:57Z"
  name: test1004
  namespace: test1005
  resourceVersion: "2947625"
  uid: e592f174-5cfd-405a-bee2-a9ad33b5f22e
type: Opaque
