---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  namespace: test3000
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      serviceAccountName: internal-kubectl
      initContainers:
      - name: db-init
        image: chiphwang/init_db:1.8
        command: ["/bin/bash", "-c", "./check_db.sh"]
        env:
        - name: dbhost_secret
          value: test3000
        volumeMounts:
        - name: tmp
          mountPath: /tmp/host
      containers:
      - image: wordpress:5.8-apache
        name: wordpress
        command: [ "/bin/bash", "-c", "source /tmp/host/launch.sh && docker-entrypoint.sh apache2-foreground" ]
        env: 
        - name: WORDPRESS_DB_PASSWORD
          value: "Chh%%67896789psh"
        - name: WORDPRESS_DB_NAME
          value: wordpress 
        - name: WORDPRESS_DB_USER
          value: admin
        ports: 
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        - name: tmp
          mountPath: /tmp/host
      volumes:
      - name: wordpress-persistent-storage
        emptyDir: {}
      - name: tmp
        emptyDir: {}
